music/urls.py
from django.conf.urls import include, url

from . import views

app_name = "music"      # to specify the same url names for different apps.

urlpatterns = [
    #  /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #  /music/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
]

website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^music/', include('music.urls', namespace='music')),
]


if settings.DEBUG:  ## if in development mode, use this:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse
# AFTER EVERY CHANGE APPLIED:
# python manage.py makemigrations music
# python manage.py sqlmigrate music 0001  - SQL look (if needed)
# python manage.py migrate  -  run migrations


class Album(models.Model):
    artist = models.CharField(max_length=250)       # table columns
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_Logo = models.FileField()          # CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):                                  # prints specified column NAMES in shell
        return self.album_title + ' - ' + self.artist


class Song(models.Model):                                       # song is a part of an album
    album = models.ForeignKey(Album, on_delete=models.CASCADE)  # delete all songs from a deleted album
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:   ## contains info about the class
        model = User  ## Using existing User model
        fields = ['username', 'email', 'password']

music/views.py
# from django.http import Http404
#from django.template import loader
from django.views.generic.edit import CreateView, UpdateView, DeleteView  # Modal Form
from django.core.urlresolvers import reverse_lazy
from .models import Album, Song
from .forms import UserForm
from django.views import generic
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'  # replaces default object_list name

    def get_queryset(self):
        return Album.objects.all()  # returns object_list by default


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album;  # What is created?
    fields = ['artist', 'album_title', 'genre', 'album_Logo']  # which there fields will be to fill in?


class AlbumUpdate(UpdateView):
    model = Album;
    fields = ['artist', 'album_title', 'genre', 'album_Logo']


class AlbumDelete(DeleteView):
    model = Album;
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)  # built in Django function

        if form.is_valid():
            user = form.save(commit=False)  # Creates an obj from form without saving it to DB
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            # returns a user if the data is correct

            user = authenticate(username=username, password=password)  # takes username & psw and check DB if they exist
            if user is not None:
                if user.is_active:
                    login(request, user)  # do login
                    return redirect('music:index')

        return render(request, self.template_name, {'form':form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Viberr - Add Album {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %} <!-- SECURITY -->
                        {% include 'music/form-template.html' %} <!-- LAYING OUT FIELDS ETC -->
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
   <title> {% block title %}Taste in Music{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Taste in Music</a>
        </div>
        <!-- ITEMS -->
        <div class="collapse navbar-collapse" id="topNavBar"> <!--topNavBar items will be collapsed (line 14)-->
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                    <button type="submit" class="btn btn-default">Search</button>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp;Add Album
                    </a>
                </li>
                 <li class="">
                    <a>
                        <span class="glyphicon glyphicon-off"></span>&nbsp;Log Out
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

    {% block body %} <!-- replaced by whatever in other html files blocks -->
    {% endblock %}

</body>

</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} Viberr - Album Details {% endblock %}

{% block body %}
<div class="container-fluid">
<div class="row">
    <div class="col-sm-2">
        <img src="{{ album.album_Logo.url }}" class="logo">
        <h1>{{ album.album_title }}</h1>
        <h3>{{ album.artist }}</h3>
        <h3>{{ album.genre }}</h3>
          <form action="{% url 'music:album-update' album.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="album_id" value="{{ album.id }}"/>
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-pencil"></span>
            </button>
          </form>
    </div>

        {% if error_message %}
            <p><strong>{{error_message}}</strong></p>
        {% endif %}

    <div class="col-sm-offset-1 col-sm-9 album-details">
        <h3>All Songs</h3>
        <table>
            <tr>
                <th>Title</th>
                <th>Audio File</th>
                <th>Favorite</th>
                <th>Actions</th>
            </tr>
        {% for song in album.song_set.all %}
            <tr>
                <td>{{ song.song_title }}</td>
                <td>{{ song.file_type }}</td>
                <td>{% if song.is_favorite %}
                    <img src="http://www.rw-designer.com/icon-image/9290-16x16x32.png/">
                {% endif %}</td>
                <td> - </td>
            </tr>
        {% endfor %}
         </table>
    </div>
</div>
</div>
{% endblock %}

<!--<ul>
    {% for song in album.song_set.all %}
    <li> {{ song.song_title }} - {{ song.file_type }} </li>
    {% endfor %}
</ul>-->

music/templates/music/form-template.html
{% for field in form %}
    <div class="group-form">
        <div class="col-sm-offset-2 col-sm-10 error-msg">
            <span class="text-danger small">{{ field.errors }}</span> <!-- if no artist name inserted for exmpl -->
        </div>
            <label class="control-label col-sm-2">{{ field.label_tag }}</label>  <!-- generates labels from fields in view -->
        <div class="col-sm-8">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
<!-- comes from base.html -->
{% extends 'music/base.html' %}

{% block body %}
    <ul>
        <li>
        {% for album in all_albums %}
            <div class="container col-offset-sm-2 col-sm-3 albumInCell">
                <a href="{% url 'music:detail' album.id %}"> <img src="{{ album.album_Logo.url }}" class="logo"></a>
                <div class="albumInfo">
                    <h2>{{ album.album_title }}</h2>
                    <h4>{{ album.artist }}</h4>
                    <h4>{{ album.genre }}</h4>
                    <form action="{% url 'music:album-delete' album.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="album_id" value="{{ album.id }}"/>
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </div>
            </div>
        {% endfor %}
        </li>
    </ul>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>Create a New Account</h2>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %} <!-- SECURITY -->
                        {% include 'music/form-template.html' %} <!-- LAYING OUT FIELDS ETC -->
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}